/*Lenguaje y autómatas
Francisco Vázquez Delgado.
Actividad: Programa para, potencia, Inversa de cadenas.
Este programa consiste en crear un programa ejecutable  que realize alagunas operaciones con cadenas, utilizando recursividad para cada 
operacion, las operaciones que el programa realiza son potencia e inversa.
En esta ventana se llevara acabo la logica del calculo de la potecnia.
*/
package pkg1546013901;

import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class Potencia extends javax.swing.JFrame {

    /**
     * Creates new form Potencia
     */
    public Potencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCadenaP = new javax.swing.JTextField();
        btnCalcularP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Spi = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnLp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Potencia de una cadena");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 40, 250, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cadena:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 80, 17);

        txtNombreCadenaP.setToolTipText("Ingresa la cadena que deseé");
        getContentPane().add(txtNombreCadenaP);
        txtNombreCadenaP.setBounds(140, 99, 140, 30);

        btnCalcularP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCalcularP.setText("Calcular");
        btnCalcularP.setToolTipText("ejecuta la operacion con lo parametros que escogio.");
        btnCalcularP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularPMouseClicked(evt);
            }
        });
        btnCalcularP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularP);
        btnCalcularP.setBounds(30, 320, 110, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Potencia:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 59, 17);

        Spi.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
        Spi.setToolTipText("En este spinner, seleccione la potencia que necesite.");
        getContentPane().add(Spi);
        Spi.setBounds(140, 140, 60, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Resultado:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 180, 70, 17);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Atras");
        jButton1.setToolTipText("Te lleva a la ventana anterior(menú principal)");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 320, 110, 30);

        btnLp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLp.setText("Limpiar");
        btnLp.setToolTipText("Limpia los campos.");
        btnLp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLpMouseClicked(evt);
            }
        });
        getContentPane().add(btnLp);
        btnLp.setBounds(150, 320, 110, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Francisco Vázquez Delgado.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 360, 160, 13);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("15460139.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 360, 51, 13);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Lenguajes y atómatas.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 10, 120, 13);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Potencia, inversa de cadenas.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 10, 143, 13);

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 360, 110);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cuadricula.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 700, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularPMouseClicked
        // Boton para calcular la potencia de  una cadena.
        String cadena=txtNombreCadenaP.getText(); //extraemos la cadena que ingreso el usuario a la caja de texto y la almacenamos en una variable.
        int potencia=(int)(Spi.getValue());//obtenemos el valor del spinner que el usuario selecciono.
        if(potencia==0){
            /*Condicionamos para la potencia 0 nos de lambda y lo mostramos en las caja de texto*/
            txtA.setText("ƛ");
        }else{
            //mandamos llamar a nuestro metodo potencia que nos ejecuta la logica de esta operacion
            potencia(cadena,potencia,""); 
            //caddena : es la palabra que el usuario ingreso
            //potencia : es el nuemro al que el usuario elevo la cadena
            //"" es el parametro donde se guardara la cadena, se concatena dependiedo la potencia
        }
        
       
        
    }//GEN-LAST:event_btnCalcularPMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Boton atras que te lleva al menu principal.
        Menu menu=new Menu(); //Creamos un objeto para mandar llama JFrame menu
        menu.setVisible(true);//En estas lineas hacemos visible la ventana menu
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnCalcularPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularPActionPerformed

    private void btnLpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLpMouseClicked
        // Este es el boton limpiar de jframe potecia.
        txtNombreCadenaP.setText(null);//en es linea lo que hacemos es limpira la caja de texto donde escribe el usuario la cadena
        txtA.setText(null);//En esta linea lo que hacemos es limpira el resultado de la cadena elevada a la enesima potencia.
        Spi.setValue(1);
    }//GEN-LAST:event_btnLpMouseClicked
//Metodo para calcular la potencia de una cadena.
    void potencia(String cadena, int potencia,String nueva){
       /*cadena: Es la cadena que ingreseo el usuario.
        potencia: el valor que selecciono el usuario para elevar la cadena a dicha potencia
        nueva:es donde se guarada la concatenacion de potencias  esta inicializada en : "" .*/
        if(potencia>0){//nos delimita las veces que el metodo se ejecutara asi mismo
            
            nueva=nueva+cadena;//nos gurada la concatenacion concecutivas segun la potencia
            potencia( cadena,  potencia-1,nueva);//el metodo se ejecuta asi mismo y en la variable potencaia esta una especio de contador que determina el numero de veces que se invocara.
            
        }else{
            txtA.setText(nueva);//despues de que termino  de invocarse el metodo, ponemos el resultado en la caja de texto para que lo muestre a los usuarions.
        
        }
        
    }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Potencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spi;
    private javax.swing.JButton btnCalcularP;
    private javax.swing.JButton btnLp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextField txtNombreCadenaP;
    // End of variables declaration//GEN-END:variables
}
